--aaa
INSET INTO ROCKIT.BOOKSERVICE (ID) VALUES (TO_CLOB('U;MU;MUU;'));
DELETE FROM ROCKIT.BOOKSERVICE WHERE TRUE; --this was a bug followed by skipped line
DELETE 
	FROM 
		ROCKIT.BOOKSERVICE 
WHERE TRUE;

